########
# NOTE
#
#  This file is duplicated in the following repos:
#    - operator-framework/kubectl-operator
#    - operator-framework/catalogd
#    - operator-framework/operator-controller
#    - operator-framework/rukpak
#
#  If you are making a change, please make it in ALL
#  of the above repositories!
#
#  TODO: Find a way to have a shared golangci config.
########

run:
  # Default timeout is 1m, up to give more room
  timeout: 4m

linters:
  enable:
  - asciicheck
  - bodyclose
  - errorlint
  - gci
  - gofmt
  - gosec
  - importas
  - misspell
  - nestif
  - nonamedreturns
  - prealloc
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - dot
      - default
      - prefix(github.com/operator-framework)

      # TODO: change this to `localmodule` when golangci-lint
      # is updated to 1.58+
      - prefix(github.com/operator-framework/kubectl-operator)
    custom-order: true

  errorlint:
    errorf: false

  importas:
    alias:
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/apimachinery/pkg/api/errors
      alias: apierrors
    - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
      alias: apiextensionsv1
    - pkg: k8s.io/apimachinery/pkg/util/runtime
      alias: utilruntime
    - pkg: "^k8s\\.io/api/([^/]+)/(v[^/]+)$"
      alias: $1$2
    - pkg: sigs.k8s.io/controller-runtime
      alias: ctrl
    - pkg: github.com/operator-framework/rukpak/api/v1alpha2
      alias: rukpakv1alpha2
    - pkg: github.com/blang/semver/v4
      alias: bsemver

output:
  formats:
    - format: tab
