before:
  hooks:
  - go mod download
builds:
- id: kubectl-operator
  main: ./
  binary: kubectl-operator
  env:
  - CGO_ENABLED=0
  asmflags:
  - all=-trimpath={{ dir .Env.PWD }}
  gcflags:
  - all=-trimpath={{ dir .Env.PWD }}
  ldflags:
  - -s
  - -w
  - -X github.com/operator-framework/kubectl-operator/internal/version.GitVersion={{.Env.GIT_VERSION}}
  - -X github.com/operator-framework/kubectl-operator/internal/version.GitCommit={{.Env.GIT_COMMIT}}
  - -X github.com/operator-framework/kubectl-operator/internal/version.GitCommitTime={{.Env.GIT_COMMIT_TIME}}
  - -X github.com/operator-framework/kubectl-operator/internal/version.GitTreeState={{.Env.GIT_TREE_STATE}}
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

archives:
- builds:
  - kubectl-operator
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE

release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
